# Base con Python 3.11
FROM python:3.11-slim-bookworm

# Java 17 y utilidades (esto no va en requirements)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-17-jdk-headless ca-certificates curl tini procps && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV PYSPARK_PYTHON=/usr/local/bin/python

WORKDIR /opt/app

# Copia e instala dependencias Python
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Usuario no root
# RUN useradd -ms /bin/bash spark && chown -R spark:spark /opt/app
# USER spark

EXPOSE 8888
CMD ["bash"]
