# docker-compose down -v
# docker-compose build
# docker-compose up

services:
  spark:
    build: .
    image: spark-lab:latest
    container_name: spark-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook --ip=0.0.0.0 --no-browser --allow-root
    init: true
    restart: unless-stopped
    entrypoint: >
      start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
